<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Instamozo extends CI_Controller {

	public function __construct()
	{
		
		parent::__construct();
		$this->load->library('instamojo');

		$this->load->library('form_validation');	
		$this->load->helper(array('form', 'url')); 	 
		$this->load->helper('cookie');
		//

		$this->load->library('session'); 
		$this->load->helper('common');
		$this->load->helper('security');
		$this->load->library('email'); 
		$this->load->library('encrypt');
		// Custom Ours
		$this->load->library('cart');
		$this->load->library('login');   
		// $this->login->check_login();	 
		$this->load->model('blog_model');   
		$this->load->model('gallery_model');   
		$this->load->model('user_model');   
		$this->load->model('commonmod_model');   
		$this->load->model('order_model');   
		$this->load->model('listing_model');   
		$this->load->model('content_model');   
		$this->load->model('checkout_model');   
		$this->load->database();   
		}


	public function index(){
		$amount = $this->session->userdata('grand_total');
        $pay = $this->instamojo->pay_request(
			$amount = $amount , 
			$purpose = "Order" , 
			$buyer_name = $this->session->userdata('bh_front_user_name'), 
			$email = $this->session->userdata('bh_front_email_id') , 
			$phone = $this->session->userdata('bh_front_mobile') ,
			$send_email = 'TRUE' , 
			$send_sms = 'TRUE' , 
			$repeated = 'FALSE'
		);
		
		$redirect_url = $pay['longurl'];
		redirect($redirect_url,'refresh');

	}

	public function get_all(){
		$result = $this->instamojo->all_payment_request();
		print_r($result);
	}


	public function pay_request(){
		$pay = $this->instamojo->pay_request( 
			$amount = "200" , 
			$purpose = "TEST" , 
			$buyer_name = "rbbqq" , 
			$email = "rajeevbbqq@gmail.com" , 
			$phone = "89xxxx2017" ,
			$send_email = 'TRUE' , 
			$send_sms = 'TRUE' , 
			$repeated = 'FALSE'
		);
		$payment_id = $pay['id'];  // <= Payment Id
							      // print_r($pay) ; <=  Prints all the data from the request

	}


	public function status()
	{
		$paymentId  = '84c04c212ccb4a8ba8c87e35ec4a2511001'  ; // $paymentId generated by Instamojo
		$status     = $this->instamojo->status($paymentId);

		print_r($status);
	}


	public function payment_status()
	{
		
		if($_REQUEST['payment_status']=='Credit' && $_REQUEST['payment_request_id']!=""){
			//$requestId = '84c04c212ccb4a8ba8c87e35ec4a2511';
			//$status    = $this->instamojo->status($requestId);
             
			 $this->session->set_userdata('payment_request_id',$_REQUEST['payment_request_id']);
			 $this->session->set_userdata('payment_status',$_REQUEST['payment_status']);
			 $this->session->set_userdata('payment_id',$_REQUEST['payment_id']);
			 $this->session->set_userdata('pay_by','Instamozo');
			redirect('search/submit_request');
		}
	}


	public function show()
	{
		$data['request_id'] = '84c04c212ccb4a8ba8c87e35ec4a2511001' ;
		$this->load->view('instamojo' ,$data);
	}

}

/* End of file example.php */
/* Location: ./application/controllers/example.php */
